:title			Selection Reporter Dialog
:filename	  	Filename:
:filename_tooltip	Enter a complete and valid filename
:value		  	Value
:on		  	On?
:name		  	Name
:check_all	  	Check All
:check_all_tooltip	Check all the items in the list
:can_not_have_empty_name	You can not enter an empty name. Please provide a sensible name.
:ok			Report
:ok_tooltip		Create a report of the elements in the list and open it in Notepad.
:close			Close
:close_tooltip		Close the dialog
:file_not_creatable	Geef een geschikte bestandnaam op een locatie waar u schrijfrechten heeft. Het is niet mogelijk om #1 aan te maken
